CPP=g++

CPPFLAGS=-march=native -msse -msse2 -msse4.1

FEATURES_UTILITY_LIB=-lopencv_core -lopencv_highgui -lopencv_imgproc -lpng

#set these to the location of your header files
OPENCV_INC_DIR=/usr/include/opencv2/core/
EIGEN_INC_DIR=./Eigen
PNG_INC_DIR=./png++
SLIC_INC_DIR=./SLIC
